import type { User } from "@/lib/types";

export const users: User[] = [
  {
    id: "u_admin",
    name: "Admin User",
    email: "admin@ynm.local",
    password: "admin123",
    role: "admin",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_plan",
    name: "Planning User",
    email: "planning@ynm.local",
    password: "planning123",
    role: "planning",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_purchase",
    name: "Purchase User",
    email: "purchase@ynm.local",
    password: "purchase123",
    role: "purchase",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_sales",
    name: "Sales User",
    email: "sales@ynm.local",
    password: "sales123",
    role: "sales",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_accounts",
    name: "Accounts User",
    email: "accounts@ynm.local",
    password: "accounts123",
    role: "accounts",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_security",
    name: "Security User",
    email: "security@ynm.local",
    password: "security123",
    role: "security",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_stores",
    name: "Stores User",
    email: "stores@ynm.local",
    password: "stores123",
    role: "stores",
    factory: "YNM-PUNE",
    isActive: true,
  },
  {
    id: "u_prod",
    name: "Production User",
    email: "production@ynm.local",
    password: "production123",
    role: "production",
    factory: "YNM-CHENNAI",
    isActive: true,
  },
];

